import Head from "next/head";
import type { FC } from "react";

const Home: FC = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Weather App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-red-400">
        <h1 className="text-3xl">Hi world</h1>
      </div>
    </>
  );
};

export default Home;
